<?php

namespace ShoppingCartBundle\Repository;


/**
 * PromotionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
use ShoppingCartBundle\Entity\Promotion;
use Doctrine\ORM\Tools\Pagination\Paginator;

class PromotionRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllActivePromotions()
    {
        return $this->createQueryBuilder("promotion")
            ->andWhere("promotion.endDate >= :now")
            ->andWhere("promotion.startDate <= :now")
            ->setParameter("now", new \DateTime("now"))
            ->getQuery()
            ->getResult();
    }


}
